kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "spring.labels" . | indent 4 }}
spec:
  selector:
    app: music
  type: {{ .Values.service.type}}  #from values | DEFAULT TO NODEPORT
  loadBalancerSourceRanges:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}
