FROM docker:27-cli AS docker-cli

FROM jenkins/inbound-agent:latest-jdk21

USER root

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker

RUN chmod +x /usr/local/bin/docker

USER jenkins
