- name: Deploy myapp on Amazin EC2 instances
  hosts: backend
  become: true

  tasks:
  - name: Ensure user exists
    ansible.builtin.user:
      name: example-user
      state: present
      shell: /bin/bash

  - name: deployment file exists
    ansible.builtin.file:
    path: /opt/myapp/install-service.sh
    mode: "0755"
    owner: "example-user"

  - name: Run deployment script
    ansible.builtin.command:
      cmd: /opt/myapp/install-service.sh