apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.service.targetPort | quote }}
  BACKEND_HOST: {{ .Values.backendService.host | quote }}
  BACKEND_PORT: {{ .Values.backendService.port | quote }}
  POSTGRES_ENABLED: {{ .Values.database.postgresEnabled | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_TABLE: {{ .Values.database.table | quote }}
  POSTGRES_SSLMODE: {{ .Values.database.sslMode | quote }}
  AWS_REGION: {{ .Values.aws.region | quote }}
  S3_BUCKET_NAME: {{ .Values.aws.s3BucketName | quote }}
  S3_SYNC_ENABLED: {{ .Values.integrations.s3Enabled | quote }}
  S3_INSTANCES_OBJECT_KEY: {{ .Values.integrations.s3ObjectKey | quote }}
  SNS_NOTIFICATIONS_ENABLED: {{ .Values.integrations.snsEnabled | quote }}
  SNS_TOPIC_ARN: {{ .Values.aws.snsTopicArn | quote }}