{{- if .Values.frontendContent.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontendContent.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
{{- end }}