nameOverride: ""
fullnameOverride: ""

namespace: devops-app

image:
  repository: zer0w1/devops-project1-backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

workerService:
  host: worker
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  name: backend-sa
  annotations: {}
  automountServiceAccountToken: false

networkPolicy:
  enabled: true